### ISSUE TITLE
crash on linux

### ISSUE THREAD

**Issue by Eneitilyn** [SS111/Minecraft-ID-Resolver#4]
i tried to run it in root terminal and i got this

root@**_-**_-**_-**_:/home/****/Desktop# java Minecraft.ID.Resolver.v1.0.8
Exception in thread "main" java.lang.NoClassDefFoundError: Minecraft/ID/Resolver/v1/0/8
Caused by: java.lang.ClassNotFoundException: Minecraft.ID.Resolver.v1.0.8
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: Minecraft.ID.Resolver.v1.0.8. Program will exit.

**Comment by SS111** [comment]
Thanks for the info. I'll take a look at this.

**Comment by SS111** [comment]
How are you launching the jar file? You appear to be typing 

> java Minecraft.ID.Resolver.v1.0.8

when the correct usage is

> java -jar Minecraft.ID.Resolver.v1.0.8

**Comment by Eneitilyn** [comment]
don't mind me im linux noob abit... well i have tried to run it with openjdk or openjre7 (i had tried even with 6..) but it just doesn't start then i tried with terminal which apparently is wrong...i will try to run it the correct way as soon as i got my hands on linux

**Comment by SS111** [comment]
Alright report back when you have the chance to try it.

**Comment by Eneitilyn** [comment]
So i did it the correct way and it seems like that program just refuses to run in "OpenJDK 7 runtime" i got version 6 like i said and i am pretty sure it's default version to run is 7 and i got this error which probably wan'ts a normal version of java
root@**_-**_-**_-**_:/home/****_/Desktop#  java -jar Minecraft.ID.Resolver.v1.0.8.jar
Unable to access jarfile Minecraft.ID.Resolver.v1.0.8.jar
root@**_-**_-**_-**_:/home/**_**/Desktop#  cd Desktop
root@**_-_**-**_-_**:/home/****_/Desktop#  java -jar Minecraft.ID.Resolver.v1.0.8.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/github/ss111/WindowMain : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: com.github.ss111.WindowMain. Program will exit.
root@**_-**_-**_-**_:/home/**_**/Desktop# 

EDIT: i removed the old java which probably comes default with debian and installed oracle java 7 and now it works even without terminal

**Comment by SS111** [comment]
This program was compiled with Java 7, which is why it worked when you installed Java 7. The error log above means that Java 6 or below was trying to run the Java 7 program. Are you sure you had OpenJDK 7? When you type "java -version" into your terminal, what does it return?

**Comment by Eneitilyn** [comment]
yes i am 100% sure i had version 7 along with version 6 and i am not sure which one is default runing i could probably gues it's 7 because it's a newer version.. i don't know how it works so...

**Comment by SS111** [comment]
Maybe it was defaulting to OpenJDK 6. Maybe not. Anyway, this appears to be fixed by using a normal Java installation. If you would like to discuss this further, reply to me on Minecraft Forum. Thanks.
